### ISSUE TITLE
4 BUGS

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#1]
Nice mod! But it can be more perfect.

**Describe the bug**
I found 4 problems in the mod betweenlands redstone 1.0.3

1. I got hurt if I silde down from the sap spit block.
![2022-08-05_23 38 55](https://user-images.githubusercontent.com/70516358/183114790-b3981513-56cb-4743-b47e-e6f8f8f67a7b.png)
I shouldn't be hurt when I silded down frome the sap spit block, but I even got 1 more damage than the situation without sap spit block.

2. The weedwood trapped chest doesn't work.
![2022-08-05_23 40 45](https://user-images.githubusercontent.com/70516358/183114827-4188cdf6-9e23-4f89-957f-adc2044207fd.png)
![2022-08-05_23 40 53](https://user-images.githubusercontent.com/70516358/183114856-56d1f60d-a946-40ff-ad58-5947baaba35d.png)
The weedwood trapped chest doesn't output any bluestone power.

3. The syrmorite detector rail doesn's work.
![2022-08-05_23 42 45](https://user-images.githubusercontent.com/70516358/183114885-44647924-bac1-490d-8f80-fd497006096d.png)
The syrmorite detector rail doesn't output any bluestone power.

4. The recipes of pitstone dispenser and pitstone dropper is wrong.
![2022-08-05_23 46 23](https://user-images.githubusercontent.com/70516358/183114901-10fe0b15-c8ff-4e8f-8ebf-3c96120ede92.png)
![2022-08-05_23 46 31](https://user-images.githubusercontent.com/70516358/183114915-4c869449-ba64-4f4f-812e-7bd4fdfb94c5.png)
![2022-08-05_23 43 13](https://user-images.githubusercontent.com/70516358/183114922-23956a08-1c8f-4b8d-ad0c-eb0fd5aa3b43.png)
![2022-08-05_23 43 53](https://user-images.githubusercontent.com/70516358/183114941-160108d1-0611-466a-ae9f-f3c19e9903f6.png)
Pitstone dispenser and pitstone dropper should made from pitstone not betweenstone. I have fixed it by crafttweaker.

**Comment by JoshieGemFinder** [comment]
okay, thank you for reporting this, i will do my best to fix them, (a few things just look like silly oversights by me), although i think i fixed the rail thing in 1.0.4

**Comment by JoshieGemFinder** [comment]
Now fixed in 1.0.5
