### ISSUE TITLE
[BUG] Wrong recipes

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#10]
**Describe the bug**  
These 2 wrong recipes occur again in the latest version. I mentioned it at #3  before
![Snipaste_2023-04-22_16-28-45](https://user-images.githubusercontent.com/70516358/233772915-fa77a68f-66ed-4b11-be84-38b7aa494fa0.png)
![Snipaste_2023-04-22_16-29-10](https://user-images.githubusercontent.com/70516358/233772922-62e94da9-28c3-4d41-8a4b-4e528980dc98.png)

Rift detector should not be used as fuel because it has no wood.
![Snipaste_2023-04-22_16-29-20](https://user-images.githubusercontent.com/70516358/233773107-64c7aaa7-4cb9-4bd8-90ea-24c0d6059402.png)

**Mod List**  
Betweenland 3.9.6
Betweenlandredstone 1.1.1

**Forge Version**  
14.23.5.2860

**To Reproduce**  
Description.

**Expected behavior**  
Description.

**Screenshots**  
Description.

**Crash Log (If Crash-Causing)**  
None

**Additional context**  
None

**Singleplayer/Server**  
single

**Comment by JoshieGemFinder** [comment]
I don't get how these recipes keep coming back, I'll go remove them again, next patch they should be gone
