### ISSUE TITLE
[BUG] Sap spit block cannot reduce the jump height of mobs.

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#11]
**Describe the bug**  
Sap spit block can reduce the jump height of the player on it, but it's invalid for mobs. I mentioned it at  #7  before, but it was not fixed in the latest version.

**Mod List**  
Betweenland 3.9.6
Betweenlandredstone 1.1.1

**Forge Version**  
14.23.5.2860

**To Reproduce**  
1. Dig a pit and place some sap spit blocks.
2. Spawn some zombies in it.
3. Zombies can escape the pit but you cannot.

**Expected behavior**  
Just like honey block in 1.15

**Screenshots**  
![Snipaste_2023-04-22_16-38-43](https://user-images.githubusercontent.com/70516358/233773554-bc1d9262-b72f-41a0-b6c8-6e09d745f1bb.png)

**Crash Log (If Crash-Causing)**  
None

**Additional context**  
None

**Singleplayer/Server**  
single

**Comment by JoshieGemFinder** [comment]
Now patched in 1.1.3
