### ISSUE TITLE
7 BUGS

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#3]
**Describe the bug**
1. Problem 1 hasn't been fixed
![2022-08-06_17 56 22](https://user-images.githubusercontent.com/70516358/183245018-cb4da286-f43d-43b8-af2e-7463ef405930.png)

2. There are some wrong recipes of mud brick observer and scabyst comparator.
![2022-08-06_18 01 30](https://user-images.githubusercontent.com/70516358/183245127-d52304fb-1fc2-43b3-a743-f0a45eeeddc3.png)
![2022-08-06_18 01 44](https://user-images.githubusercontent.com/70516358/183245131-9f795788-20d6-4f3c-9c39-d98c540724cc.png)

3. The texture of scabyst reapter is a part of vanilla bedrock, not betweenlands bedrock.
![2022-08-06_17 53 23](https://user-images.githubusercontent.com/70516358/183245193-ad48908f-7f04-4d8a-bdd5-44bfe9b571ae.png)

4. The block of thebetweenland can be activated by both redstone power and bluestone power.
![2022-08-06_18 00 18](https://user-images.githubusercontent.com/70516358/183245301-ac120358-7168-4c61-a267-4095214bb787.png)

5. The power source of thebetweenland can both provide redstone power and bluestone power.
![2022-08-06_18 03 33](https://user-images.githubusercontent.com/70516358/183245438-b244d1b9-12b7-4fbe-88d7-491f4f79f3d4.png)

6. Piston cannot push mud brick piston, but mud brick piston can. And the sticky one is the same.
![2022-08-06_18 05 30](https://user-images.githubusercontent.com/70516358/183245506-5da66355-d873-4d46-8947-337ad0feadf1.png)
![2022-08-06_18 10 34](https://user-images.githubusercontent.com/70516358/183245509-84784556-7c95-4d74-bda8-f7dc486cea20.png)

7. Block of white pear is not available in creative mode and JEI and Waila.
![2022-08-06_17 55 01](https://user-images.githubusercontent.com/70516358/183245557-4acab5f3-eb1d-4cab-b049-de39123d95f6.png)

Maybe the chinese language file can be contained in the next version.

**Comment by JoshieGemFinder** [comment]
Are you using the latest version? I am not running into any of these issues (apart from the pear one, but that's kind of a joke and on purpose)
I'll go over it all again and release a patch

**Comment by GoldenTotem** [comment]
> Are you using the latest version? I am not running into any of these issues (apart from the pear one, but that's kind of a joke and on purpose)

Yes, I'm using the latest version 1.0.5 and thebetweenland 3.8.1
![2022-08-06_19 19 03](https://user-images.githubusercontent.com/70516358/183246699-6760e5b4-a312-457b-9184-54efa2509456.png)
.

**Comment by JoshieGemFinder** [comment]
okay so the observer/comparator one is just a backup storage system (basically an online one) i'm using automatically undeleted the old recipe files
the betweenlands power sources (the ones added by the betweenlands directly, i mean) are meant to be able to able to power both vanilla and scabyst redstone, that's a feature, not a bug
i'll change the repeater texture to BL bedrock
the piston issue (for BL pistons and the sticky blocks) is just me not wanting to have to edit vanilla MC source code, as that can cause incompatibilities with other mods, I'm making an addon mod that'll use mixins to fix a few issues like this

**Comment by GoldenTotem** [comment]
Another problem: If the slime block is pushed by mud brick piston, it cannot drive other block. But sludgy block and sap spit block are ok.
![2022-08-06_19 16 51](https://user-images.githubusercontent.com/70516358/183246949-cd7f3808-49a1-441c-8582-e0b87e5e62d8.png)
![2022-08-06_19 17 19](https://user-images.githubusercontent.com/70516358/183246930-f9cafa1b-39b6-453b-877f-06eb4e09ba67.png)
![2022-08-06_19 17 45](https://user-images.githubusercontent.com/70516358/183246939-62062b00-4bbe-4a4c-8d16-2ba1f3c39694.png)

**Comment by GoldenTotem** [comment]
Another problem: If you put the scabyst dust block first, then put the trapdoor, the trapdoor won't be activated. But if you reverse the order, there is no problem.
![2022-08-06_19 38 45](https://user-images.githubusercontent.com/70516358/183247438-852da3af-9f94-4c52-b6ab-53e4c139c462.png)

**Comment by JoshieGemFinder** [comment]
that last one is interesting, although i can't replicate it in a world, but could you put these last two in separate issues so i can check them off individually? (makes keeping track of them easier) thanks

**Comment by GoldenTotem** [comment]
> that last one is interesting, but could you put these last two in separate issues so i can check them off individually? (makes keeping track of them easier) thanks

OK

**Comment by JoshieGemFinder** [comment]
i've fixed the issues, but don't have enough time to make sure nothing else has cropped up and to upload to curseforge, so i'm going to go to sleep now bc it's late
gonna mark as closed since i've fixed the initial problems this issue came up with
