### ISSUE TITLE
1 BUG

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#4]
**Describe the bug**
If the slime block is pushed by mud brick piston, it cannot drive other block. But sludgy block and sap spit block are ok.
![2022-08-06_19 16 51](https://user-images.githubusercontent.com/70516358/183247608-3eb489b4-49ec-4cd3-aec4-ea2e2db72348.png)
![2022-08-06_19 17 19](https://user-images.githubusercontent.com/70516358/183247618-99e46b5e-f7e7-4035-a2d9-54dd63e4c4f7.png)
![2022-08-06_19 17 45](https://user-images.githubusercontent.com/70516358/183247620-300579d2-d282-48e9-bc21-866ba546cf04.png)

**Comment by JoshieGemFinder** [comment]
now fixed
