### ISSUE TITLE
1 BUG

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#5]
**Describe the bug**
If you put the scabyst dust block first, then put the trapdoor, the trapdoor won't be activated. But if you reverse the order, there is no problem.
![2022-08-06_19 38 45](https://user-images.githubusercontent.com/70516358/183247668-61b21f73-72ff-44e8-a97c-87ae420dd10b.png)

**Comment by JoshieGemFinder** [comment]
I don’t have enough info to patch this, I can’t replicate it in a world, please use the full bug report template
