### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#6]
**Describe the bug**  
If you put the scabyst dust block first, then put the trapdoor, the trapdoor won't be activated. But if you reverse the order, there is no problem.

**Mod List**  
Only
betweenland 3.8.1
betweenlandredstone 1.0.6

**Forge Version**  
14.23.5.2860

**To Reproduce**  
In gif

**Expected behavior**  
Like the redstone in vanilla.

**Screenshots**  
![Minecraft 1 12 2 2022-10-18 23-26-34 00_00_01-](https://user-images.githubusercontent.com/70516358/196475155-a8776de9-6961-4383-8860-b9ba93dc98c0.gif)

**Crash Log (If Crash-Causing)**  

**Additional context**  

**Singleplayer/Server**  
single

**Comment by JoshieGemFinder** [comment]
do you have scabyst exclusivity on in the config? it causes a lot of bugs and is not really recommended

**Comment by GoldenTotem** [comment]
> do you have scabyst exclusivity on in the config? it causes a lot of bugs and is not really recommended
In cfg file
    B:scabystExclusivity=true
And the default setting is true, it means scabyst and redstone are independent of each other.
Do you mean I should set scabystExclusivity to false?

**Comment by JoshieGemFinder** [comment]
default setting should be false, setting scabystExclusivity to true is not recommended
