### ISSUE TITLE
[BUG] Sap Spit and Sludge blocks have no 'sliding down' sound when sliding down on the sides of them.

### ISSUE THREAD

**Issue by MagmaSlime123** [JoshieGemFinder/Betweenlands-Redstone#8]
**Describe the bug**  
Title.

**Mod List**  
Happens with or without other mods.

**Forge Version**  
2860.

**To Reproduce**  
Slide down the side of a Sap Spit and Sludge block.

**Expected behavior**  
There to be some kind of new sound, such as the 1.15 honey block sliding sound.

**Screenshots**  
N/A.

**Crash Log (If Crash-Causing)**  
N/A.

**Additional context**  
I suggested this on your Discord. I doubt you care about it though.

**Singleplayer/Server**  
Both.

**Comment by JoshieGemFinder** [comment]
Hmmm I thought I had added a sound for that, I will have to look into it when I can.

**Comment by JoshieGemFinder** [comment]
Okay yes the development version of the mod has the 1.15 sounds in it for the sap blocks, so when the correct PRs are accepted on actual betweenlands I should be able to update the mod safely.

**Comment by MagmaSlime123** [comment]
Has the blank inventory slot thing bee fixed too?

![image](https://user-images.githubusercontent.com/51277766/222938582-03015121-08a7-48a8-b495-30fe0f1a4f3f.png)
