### ISSUE TITLE
[BUG] There will be an empty subtitle when you jump on the sap spit block

### ISSUE THREAD

**Issue by GoldenTotem** [JoshieGemFinder/Betweenlands-Redstone#9]
**Describe the bug**  
Title

**Mod List**  
Betweenland 3.9.6
Betweenlandredstone 1.1.1

**Forge Version**  
14.23.5.2860

**To Reproduce**  
1. Place a sap spit block.
2. Jump on it.
3. Look at the subtitle area.

**Expected behavior**  
A normal subtitle.

**Screenshots**  
![Snipaste_2023-04-22_16-21-20](https://user-images.githubusercontent.com/70516358/233772688-d170ee7f-a0fe-42d3-bfad-a651aa59a343.png)

**Crash Log (If Crash-Causing)**  
None

**Additional context**  
None

**Singleplayer/Server**  
Singleplayer

**Comment by JoshieGemFinder** [comment]
I probably just forgot a lang file entry or two, shouldn't be too hard to fix

**Comment by JoshieGemFinder** [comment]
Now patched in 1.1.3
